[unstable]
build-std = ['std', 'panic_abort']

[build]
target = "wasm32-unknown-unknown"
# for shared memory between WASM workers
# rustflags = '-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals'
