[package]
name = "wasm_test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.80"
image = "0.24.2"
imageproc = "*"
rusttype = "*"
web-sys = "*"
js-sys = "0.3.57"