[package]
name = "jakes-photo-booth"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
opt-level = 's'

[lib]
crate-type = ["cdylib"]
path = './lib.rs'

[dependencies]
wasm-bindgen = "0.2.80"
image = "0.24.2"
imageproc = "*"
rusttype = "*"
web-sys = "*"
js-sys = "0.3.57"
