name: Pull Request Testing

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'test'
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  dry-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NPM
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Rust
        run: |
          chmod +x ./bin/*
          ./bin/install-rust.sh

      - name: Compile WASM
        run: npm run compile:release

      - name: Dry build site
        run: npm run build

      - name: Check contents
        run: ls ./dist
